sudo: required

install:
  - sudo apt-get -y update
  - sudo apt-get install -y tcl tcl8.4-dev


script:
  - curl -s https://get.nextflow.io | bash 
  - ./nextflow

notifications:
  irc:
    channels:
      - "irc.freenode.org#inasafe"
    use_notice: true

  email:
    - helge.dzierzon@plantandfood.co.nz
